name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Increment tag
        id: increment_tag
        run: |
            current_tag=$(curl -s "https://hub.docker.com/v2/repositories/dasklyarov/myapp/" | jq '.pull_count')
            incremented_tag=$((current_tag + 1))
            echo "::set-output name=tag_incremented::$incremented_tag"
        

      - name: Update image tag for container flask-server in app-deployment.yaml
        run: |

          sudo apt-get install sed
          sed -i 's/image: dasklyarov\/myapp:[A-Za-z0-9]*/image: dasklyarov\/myapp:${{ steps.increment_tag.outputs.tag_incremented }}/' ./my-app/app-deployment.yaml
    
      - name: Commit and Push changes
        run: |
            git config --local user.email ${{ secrets.GIT_EMAIL }}
            git config --local user.name ${{ secrets.GIT_USER }}
            git add ./my-app/app-deployment.yaml
            git commit -m "Update image tag in app-deployment.yaml"
            git push origin main
          

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./my-app
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/myapp:${{ steps.increment_tag.outputs.tag_incremented }}

      - name: Push changes
        run: |
            git push file:///Users/danielsklyarov/Azure1090/demo-project/.git HEAD:main
        