name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest
        
      - name: Validate tag from Docker meta
        id: validate_tag
        run: |
          current_tag=${{ steps.meta.outputs.labels['org.opencontainers.image.version'] }}
          if ! [[ "$current_tag" =~ ^[0-9]+$ ]]; then
            echo "::set-output name=tag_valid::false"
          else
            echo "::set-output name=tag_valid::true"
          fi

      - name: Increment tag
        id: increment_tag
        run: |
          current_tag=${{ steps.meta.outputs.labels['org.opencontainers.image.version'] }}
          if [[ "$current_tag" =~ ^[0-9]+$ ]]; then
            incremented_tag=$((current_tag + 1))
          else
            incremented_tag=2
          fi
          echo "::set-output name=tag_incremented::$incremented_tag"

      - name: Update image tag for container flask-server in deployment.yaml
        uses: loveholidays/gitops-action-yaml-updater@v1.0
        with:
          mode: IMAGE_TAG
          container-name: flask-server
          new-image-tag: ${{ secrets.DOCKERHUB_USERNAME }}/myapp:${{ steps.increment_tag.outputs.tag_incremented }}
          filepath: ./my-app/app-deployment.yaml

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./my-app
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/myapp:${{ steps.increment_tag.outputs.tag_incremented }}
