name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest
        
      - name: Increment tag
        id: increment_tag
        run: |
          echo "::set-output name=tag::$((${{ steps.meta.outputs.tag }} + 1))"

      - name: Update app-deploynet.yaml
        uses: rmeneely/update-yaml@v1
        with:
          infile: my-app/app-deployment.yaml
          varlist: 'spec.template.spec.containers[0].image=${{ secrets.DOCKERHUB_USERNAME }}/myapp:${{ steps.increment_tag.outputs.tag }}'
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./my-app
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/myapp:${{ steps.increment_tag.outputs.tag }}
          

