name: Docker Build and Deployment

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger the build and deployment on

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get latest Git tag
        id: get_latest_tag
        run: |
          echo "::set-output name=tag::$(git describe --tags --abbrev=0)"

      - name: Increment tag
        id: increment_tag
        run: |
          echo "::set-output name=tag::$((${{ steps.get_latest_tag.outputs.tag }} + 1))"

      - name: Tag Git commit
        run: |
          git config user.email "sklyarov1998ne@gmail.com"
          git config user.name "dasklyarov"
          git tag ${{ steps.increment_tag.outputs.tag }}
          git push origin ${{ steps.increment_tag.outputs.tag }}
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./my-app
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/myapp:${{ steps.increment_tag.outputs.tag }}

      - name: Update app-deployment.yaml
        run: |
          sed -i "s/{{imageTag}}/${{ steps.increment_tag.outputs.tag }}/g" ./my-app/app-deployment.yaml
