name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest
        
      - name: Increment tag
        id: increment_tag
        run: |
          echo "::set-output name=tag::$((${{ steps.meta.outputs.tag }} + 1))"

      - name: Update image tag for container nginx in deployment.yaml
        uses: loveholidays/gitops-action-yaml-updater@v1.0
        with:
            mode: IMAGE_TAG
            container-name: flask-server
            new-image-tag: ${{ secrets.DOCKERHUB_USERNAME }}-${{ steps.increment_tag.outputs.tag }}
            dir: ./my-app
            files: ./my-app/app-deployment.yaml


      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./my-app
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/myapp:${{ steps.increment_tag.outputs.tag }}
          

