name: Docker Build and Deployment

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get latest Git tag
        id: get_latest_tag
        run: |
          echo "::set-output name=tag::$(git describe --tags --abbrev=0)"

      - name: Increment tag
        id: increment_tag
        run: |
          echo "::set-output name=tag::$((${{ steps.get_latest_tag.outputs.tag }} + 1))"

      - name: Check if tag exists
        id: check_tag
        run: |
          git fetch --tags
          git rev-parse -q --verify "refs/tags/${{ steps.increment_tag.outputs.tag }}"

      - name: Tag Git commit
        run: |
          git config user.email "sklyarov1998ne@gmail.com"
          git config user.name "dasklyarov"

          if [ -z "${{ steps.check_tag.outputs.stdout }}" ]; then
           
